// Generated by CoffeeScript 1.4.0
var constants;

constants = {};

constants.STREAM_PLAYBACK = 0;

constants.STREAM_CAPTURE = 1;

constants.NONBLOCK = 0x00000001;

constants.ASYNC = 0x00000002;

constants.ABORT = 0x00008000;

constants.NO_AUTO_RESAMPLE = 0x00010000;

constants.NO_AUTO_CHANNELS = 0x00020000;

constants.NO_AUTO_FORMAT = 0x00040000;

constants.NO_SOFTVOL = 0x00080000;

constants.STATE_OPEN = 0;

constants.STATE_SETUP = 1;

constants.STATE_PREPARED = 2;

constants.STATE_RUNNING = 3;

constants.STATE_XRUN = 4;

constants.STATE_DRAINING = 5;

constants.STATE_PAUSED = 6;

constants.STATE_SUSPENDED = 7;

constants.STATE_DISCONNECTED = 8;

constants.STATE_LAST = constants.STATE_DISCONNECTED;

constants.ACCESS_MMAP_INTERLEAVED = 0;

constants.ACCESS_MMAP_NONINTERLEAVED = 1;

constants.ACCESS_MMAP_COMPLEX = 2;

constants.ACCESS_RW_INTERLEAVED = 3;

constants.ACCESS_RW_NONINTERLEAVED = 4;

constants.ACCESS_LAST = constants.ACCESS_RW_NONINTERLEAVED;

constants.FORMAT_UNKNOWN = -1;

constants.FORMAT_S8 = 0;

constants.FORMAT_U8 = 1;

constants.FORMAT_S16_LE = 2;

constants.FORMAT_S16_BE = 3;

constants.FORMAT_U16_LE = 4;

constants.FORMAT_U16_BE = 5;

constants.FORMAT_S24_LE = 6;

constants.FORMAT_S24_BE = 7;

constants.FORMAT_U24_LE = 8;

constants.FORMAT_U24_BE = 9;

constants.FORMAT_S32_LE = 10;

constants.FORMAT_S32_BE = 11;

constants.FORMAT_U32_LE = 12;

constants.FORMAT_U32_BE = 13;

constants.FORMAT_FLOAT_LE = 14;

constants.FORMAT_FLOAT_BE = 15;

constants.FORMAT_FLOAT64_LE = 16;

constants.FORMAT_FLOAT64_BE = 17;

constants.FORMAT_IEC958_SUBFRAME_LE = 18;

constants.FORMAT_IEC958_SUBFRAME_BE = 19;

constants.FORMAT_MU_LAW = 20;

constants.FORMAT_A_LAW = 21;

constants.FORMAT_IMA_ADPCM = 22;

constants.FORMAT_MPEG = 23;

constants.FORMAT_GSM = 24;

constants.FORMAT_SPECIAL = 31;

constants.FORMAT_S24_3LE = 32;

constants.FORMAT_S24_3BE = 33;

constants.FORMAT_U24_3LE = 34;

constants.FORMAT_U24_3BE = 35;

constants.FORMAT_S20_3LE = 36;

constants.FORMAT_S20_3BE = 37;

constants.FORMAT_U20_3LE = 38;

constants.FORMAT_U20_3BE = 39;

constants.FORMAT_S18_3LE = 40;

constants.FORMAT_S18_3BE = 41;

constants.FORMAT_U18_3LE = 42;

constants.FORMAT_U18_3BE = 43;

constants.FORMAT_G723_24 = 44;

constants.FORMAT_G723_24_1B = 45;

constants.FORMAT_G723_40 = 46;

constants.FORMAT_G723_40_1B = 47;

constants.FORMAT_DSD_U8 = 48;

constants.FORMAT_DSD_U16_LE = 49;

constants.FORMAT_LAST = constants.FORMAT_DSD_U16_LE;

module.exports = constants;
