// Generated by CoffeeScript 1.4.0
var k, stream, v, _ref;

stream = require('./stream');

exports.Pcm = require('../build/Release/alsa').Pcm;

exports.Capture = stream.Capture;

exports.Playback = stream.Playback;

_ref = require('./constants');
for (k in _ref) {
  v = _ref[k];
  exports[k] = v;
}
